version: "4.12"

services:
  app:
    container_name: "pasar-online"
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    env_file:
      - .env
